export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_ERROR = "REMOVE_FROM_CART_ERROR";

export const FETCH_CART_PRODUCT_REQUEST = "FETCH_CART_PRODUCT_REQUEST";
export const FETCH_CART_PRODUCT_SUCCESS = "FETCH_CART_PRODUCT_SUCCESS";
export const FETCH_CART_PRODUCT_ERROR = "FETCH_CART_PRODUCT_ERROR";